
---

- name: Update the machine
  tags: upd
  yum:
    update_only: yes

- name: Install General Essential packages
  tags: essentials
  yum:
    name:
      - nano
      - net-tools
      - tcpdump
      - nmap
      - wireshark
      - git
      - wget
      - iproute
      - psmisc
      - yum-utils
      - chrony
      - telnet
      - iptables-services
      - conntrack
      - gcc
      - make
      - elfutils-libelf-devel
      - kernel-devel
      - libnl3-devel
      - iptables-devel
      - tar
      - python36
    state: present

- name: Add VPP Repository to yum repo list
  tags: shell
  shell: curl -s https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh | sudo bash

- name: Clear the Cache
  command: yum clean all

- name: Update yum Cache - mit Command
  tags: man
  command: yum -q makecache -y --disablerepo='*' --enablerepo='fdio_release'


- name: Update yum Cache - mit Module
  tags: module
  yum:
    update_cache: yes
    enablerepo: "fdio_master"
    disablerepo: "*"
    state: present

- name: Install General Essential packages
  tags: danach
  yum:
    name:
      - vpp
      - vpp-plugins
      - vpp-devel
      - vpp-debuginfo
      - vpp-ext-deps
      - vpp-api-python
      - vpp-api-lua
    state: present

- name: Install vpp-api-java Package
  tags: danach
  yum:
    name: vpp-api-java
    state: present
    skip_broken: yes

- name: Install several packages in case of deleting iptables
  tags: iptables
  yum:
    name:
      - iptables
      - iproute
      - dhclient
      - plymouth
      - initscripts
      - kbd
      - kexec-tools
      - dracut
      - firewalld
      - iptables-services
      - mlocate
    state: present


  
  
  user@T:~# # https://fedoraproject.org/wiki/EPEL
user@T:~# yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
user@T:~# yum install dkms


yum install git automake libtool


git clone https://github.com/NICMx/Jool.git

 /sbin/dkms install Jool/
 
 
 cd Jool/
user@T:~$ ./autogen.sh
user@T:~$ ./configure
user@T:~$ make
user@T:~# make install



