---
- hosts: localhost
  gather_facts: true
  connection: local

  vars_prompt:
    - name: "attack_scenario"
      prompt: "Please Enter Your Attacking Scenario, 'A' or 'B'"
      private: no

  tasks:
  - include_role:
      name: atk_deb
    when: ansible_distribution|string == 'Debian'
          or ansible_distribution|string == 'Ubuntu'
 
  - include_role:
      name: atk_centos
    when: ansible_distribution|string == 'CentOS'
 
 
  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin
