---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  connection: local

  tasks:
  - include_role:
      name: cernet_centos
    when: ansible_distribution == 'CentOS'
  

  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin
