---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  connection: local

  tasks:
#  - include_role:
#      name: jool_debian
#    when: 
#      - ansible_distribution == 'Debian' 
#        or ansible_distribution == 'Ubuntu'
    
  - include_role:
      name: jool_centos
    when: ansible_distribution == 'CentOS'
  
  - name: Compile everything.
    tags: last
    shell: |
      ./configure
      make
      make install
    args:
      chdir: /usr/src/jool-4.1.7/

    
  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Create networking (IP routes) file
    tags: routing
    ansible.builtin.template:
      src: MAPE-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
