---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: true
  connection: local

  tasks:
  - include_role:
      name: jool_alma
    when: 
      - ansible_distribution|string == 'AlmaLinux'   
      
  - include_role:
      name: jool_centos
    when: ansible_distribution == 'CentOS'
  

  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Create networking (IP routes) file
    tags: routing
    ansible.builtin.template:
      src: MAPE-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
