---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: no
  connection: local

  tasks:
  - name: Update the machine
    tags: upd
    yum:
      update_only: yes

  - name: Install General Essential packages
    tags: essentials
    yum:
      name:
        - nano
        - net-tools
        - tcpdump
        - nmap
        - wireshark
        - git
        - wget
        - iproute
        - psmisc
        - yum-utils
        - chrony
        - telnet
        - iptables-services
        - conntrack
        - gcc
        - pygpgme
        - mbedtls
        - python36
      state: present

  - name: Add VPP Repository to yum repo list
    tags: uri
    uri:
      url: https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh

  - name: Add VPP Repository to yum repo list
    tags: uri-2
    get_url:
      url: https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh 
      dest: /etc/yum.repos.d

  - name: Add VPP Repository to yum repo list
    command: curl -s https://packagecloud.io/install/repositories/fdio/release/script.rpm.sh | sudo bash

  - name: Clear the Cache
    command: yum clean all

  - name: Update yum Cache - mit Command
    tags: man
    command: yum -q makecache -y --disablerepo='*' --enablerepo='fdio_release'


  - name: Update yum Cache - mit Module
    tags: module
    yum:
      update_cache: yes
      enablerepo: "fdio_master"
      disablerepo: "*"
      state: present

  - name: Install General Essential packages
    tags: danach
    yum:
      name:
        - vpp
        - vpp-plugins
        - vpp-devel
        - vpp-debuginfo
        - vpp-ext-deps
        - vpp-api-python
        - vpp-api-lua
      state: present

  - name: Install vpp-api-java Package
    tags: danach
    yum:
      name: vpp-api-java
      state: present
      skip_broken: yes
 
  - name: Install several packages in case of deleting iptables
    tags: iptables
    yum:
      name:
        - iptables
        - iproute
        - dhclient
        - plymouth
        - initscripts
        - kbd
        - kexec-tools
        - dracut
        - firewalld
        - iptables-services
        - mlocate
      state: present

  - name: Start VPP Service
    tags: service
    systemd:
      name: vpp
      state: restarted
      enabled: yes
   
  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Create networking (IP routes) file
    tags: routing
    ansible.builtin.template:
      src: MAPE-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
