---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: no
  connection: local

  tasks:
  - include_role:
      name: debian
    when: 
      - ansible_distribution == 'Debian' 
        or ansible_distribution == 'Ubuntu'
    
  - include_role:
      name: debian
    when: ansible_distribution == 'CentOS'
  

  - name: Start VPP Service
    tags: service
    systemd:
      name: vpp
      state: restarted
      enabled: yes
   
  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin

  - name: Create networking (IP routes) file
    tags: routing
    ansible.builtin.template:
      src: MAPE-networking.txt
      dest: /root/networking.sh
      owner: root
      mode: '755'
