---
- hosts: localhost
  gather_facts: false
  connection: local


  tasks:
  - name: Update the machine
    tags: upd
    yum:
      update_only: yes

  - name: Install General Essential packages
    tags: essentials
    yum:
      name:
        - nano
        - net-tools
        - tcpdump
        - nmap
        - wireshark
        - git
        - wget
        - iproute
        - psmisc
        - yum-utils
        - chrony
        - telnet
        - iptables-services
        - conntrack
        - gcc
        - make
        - tar
        - libselinux-python3
      state: present

  - name: Create Jool Networking file on IPv4 Server
    tags: jool
    template:
      src: jool-net-server.txt
      dest: /root/jool-net.sh
      owner: root
      mode: '755'


  - name: Set the timezone.
    tags: NTP
    shell: |
      timedatectl set-ntp true
      timedatectl set-timezone Europe/Berlin


  - name: Creates a cron file
    tags: cron
    ansible.builtin.cron:
      name: cron test
      weekday: "*"
      minute: "*"
      hour: "*"
      user: root
      job: "/root/jool-net.sh"

  - name: Creates an entry like "@reboot"
    tags: cron
    ansible.builtin.cron:
      name: "a job for reboot"
      user: root
      special_time: reboot
      job: "/root/jool-net.sh"
