---
- name: Update the machine
  apt:
    name: "*"
    state: latest

- name: Install General Essential packages
  apt:
    name:
      - python3
      - pip
      - ssh
      - nano
      - net-tools
      - tcpdump
      - nmap
      - wireshark
      - git
      - wget
      - psmisc
      - chrony
      - telnet
      - conntrack
      - gcc
      - curl
      - sudo
    state: present

- name: Add VPP Repository to yum repo list
  shell: curl -L https://packagecloud.io/fdio/release/gpgkey | sudo apt-key add -
  
- name: Install General Essential packages
  apt:
    name:
      - vpp
      - vpp-plugin-core
      - vpp-plugin-dpdk
      - vpp-api-python
      - python3-vpp-api
      - vpp-dpg
      - vpp-dev
    state: present

- name: Install several packages in case of deleting iptables
  apt:
    name:
      - iptables
      - iproute
      - dhclient
      - plymouth
      - initscripts
      - kbd
      - kexec-tools
      - dracut
      - firewalld
      - iptables-services
      - mlocate
    state: present
