---
- name: Update the machine
  apt:
    name: "*"
    state: latest

- name: Install General Essential packages
  apt:
    name:
      - python3
      - pip
      - ssh
      - nano
      - net-tools
      - tcpdump
      - nmap
      - wireshark
      - git
      - wget
      - psmisc
      - chrony
      - telnet
      - conntrack
      - gcc
      - curl
      - sudo
      - iptables
    state: present

- name: Add VPP Repository to yum repo list
  shell: curl -s https://packagecloud.io/install/repositories/fdio/release/script.deb.sh | sudo bash
  
- name: Install General Essential packages
  apt:
    name:
      - vpp
      - vpp-plugin-core
      - vpp-plugin-dpdk
#      - vpp-api-python
      - python3-vpp-api
#      - vpp-dpg
      - vpp-dev
    state: present
