---
- name: Update the machine
  yum:
    update_only: yes

- name: Install General Essential packages
  yum: 
    name: 
      - nano
      - net-tools
      - tcpdump
      - nmap
      - wireshark
      - git
      - wget
      - iproute
      - psmisc
      - yum-utils
      - chrony
      - telnet
      - iptables-services
      - conntrack
      - gcc
      - bridge-utils
      - hping3
      - bind-utils
    state: present

- name: Clone Scapy Repo
  git:
    repo: https://github.com/secdev/scapy.git
    dest: /root/scapy
    clone: yes
    update: yes
  when:
    - attack_scenario == "a"

- name: Create Networking and script 
  ansible.builtin.template:
    src: atk-net.txt
    dest: /root/jool-net.sh
    owner: root
    mode: '755'
