---
- name: Update the machine
  tags: upd
  apt:
    name: "*"
    state: latest

- name: Install General Essential packages
  tags: essentials
  apt:
    name:
      - nano
      - net-tools
      - tcpdump
      - nmap
      - wireshark
      - git
      - wget
      - psmisc
      - chrony
      - telnet
      - conntrack
      - gcc
      - make
      - pkg-config
      - build-essential
      - libnl-genl-3-dev
#      - elfutils-libelf-devel
#      - iptables-devel
#      - iptables-dev
      - libxtables-dev
      - autoconf
      - libtool
      - dkms
#      - kernel-devel
#      - libnl3-devel
#      - iptables-devel
      - tar
#      - python36
      - automake
    state: latest


- name: Grab the kernel header name   
  shell: uname -r
  register: headers

- name: Install Linux headr for the designated kernel   
  shell: apt-get install linux-headers-"{{ headers.stdout }}"

# If the above Module didn't work: -
# yum update -y
# yum upgrade -y
# reboot

- name: Clear the Cache
  command: apt-get clean all


#- name: Clone Jool-repo
#  tags: noo
#  git:
#    repo: https://github.com/NICMx/Jool.git
#   dest: /jool
#    clone: yes
#   update: yes


- name: Download jool
  tags: jool
  #shell: wget https://github.com/NICMx/Jool/releases/download/v4.1.7/jool-4.1.7.tar.gz 
  shell: wget https://github.com/NICMx/Jool/releases/download/v4.2.0-rc2/jool-4.2.0.rc2.tar.gz
  args:
    chdir: /usr/src

- name: Decompress jool files
  tags: jool
  shell: tar -xzf jool-4.2.0.rc2.tar.gz
  args:
    chdir: /usr/src


- name: install Jool
  tags: jool
  shell: /sbin/dkms install -m jool -v 4.2.0
   
  
#- name: Compile everything.
#  tags: last
#  shell: |
#    ./configure
#    make
#    make install
#  args:
#    chdir: /usr/src/jool-4.2.0/


- name: Double-Check if Jool is installed.
  tags: check
  shell: /sbin/dkms status
  register: jool_status

- name: Double-Check jool status output
  tags: check    
  debug:
    msg: "{{ jool_status.stdout }}"

- name: Fail when Jool was Not installed successfully.
  tags: check    
  fail:
    msg: "Jool was NOT installed successfully"
  when: "'installed' not in jool_status.stdout "


- name: Grabb Physical Machine hostname
  tags: dn
  shell: hostname
  register: device_name

- name: Create Jool Networking file in CE Router 
  tags: jool
  ansible.builtin.template:
    src: CE.txt
    dest: /CE.sh
    owner: root
    mode: '755'
  when: "'-ce' in device_name.stdout"


- name: Create Jool Networking file in BR Router 
  tags: jool
  ansible.builtin.template:
    src: BR.txt
    dest: /BR.sh
    owner: root
    mode: '755'
  when: "'-br' in device_name.stdout"
